name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: ./FLang-RTC

  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3, microsoft/setup-msbuild@v1.0.2
      
    - name: Print compiler version and language standard
      run: |
        cl.exe /version
        cl.exe /d1reportSingleClassLayout- /std:c++20 <nul | findstr /C:"using C++" /C:"class layout for"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:LanguageStandard=c++20 /p:PlatformToolset=v142 ${{env.SOLUTION_FILE_PATH}}
